services:
  mariadb:
    image: docker.io/bitnami/mariadb:11.4
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
  wordpress:
    image: docker.io/bitnami/wordpress:6
    ports:
      - '8081:8080'
      - '8443:8443'
    volumes:
      - 'wordpress_data:/bitnami/wordpress'
      # plugin mount cannot be inside named volume at least initially,
      # workaround by symlinking plugin into plugins dir
      - '.:/bitnami/phel-wp-plugin'
    depends_on:
      - mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - WORDPRESS_USERNAME=admin
      - WORDPRESS_PASSWORD=password
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress

volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
